language: python
python:
  - "3.9"

before_install:
  - sudo apt-get update
  - sudo apt-get install libssl-dev openssl
  - python -m venv myenv
  - source myenv/bin/activate

install:
  - pip install poetry
  - poetry install

script:
  - poetry run pytest test