version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python -
      - run:
          name: Install Dependencies with Poetry
          command: |
            poetry install
      - run:
          name: Run Tests with Poetry
          command: |
            poetry run pytest test
