version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python
            export PATH="$HOME/.poetry/bin:$PATH"
            source $HOME/.poetry/env
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pyproject.toml" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            source $HOME/.poetry/env
            poetry install
      - save_cache:
          paths:
            - ~/.cache/pypoetry/virtualenvs
          key: v1-dependencies-{{ checksum "pyproject.toml" }}
      - run:
          name: Run Tests
          command: |
            source $HOME/.poetry/env
            poetry run pytest
