version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Poetry
          command: pip install poetry
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest

  # deploy: # this can be any name you choose
  #   executor: python/default
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - heroku/deploy-via-git:
  #         force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - build_and_test
      # - deploy:
      #     requires:
      #       - build_and_test # only deploy if the build_and_test job has completed
      #     filters:
      #       branches:
      #         only: main # only deploy when on main
