version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python -
            export PATH="$HOME/.poetry/bin:$PATH"
            source $HOME/.poetry/env
      - run:
          name: Install Dependencies with Poetry
          command: |
            poetry install
      - run:
          name: Run Tests with Poetry
          command: |
            source $HOME/.poetry/env
            poetry run pytest test
